baseurl = "https://chen.fun"
languageCode = "en"
title = "陈华 / Hua Chen"
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License."
pygmentsUseClasses = true
email = "hua@chen.fun"
author = "CHEN, Hua"

[markup]
  defaultMarkdownHandler = "pandoc"

[permalinks]
    zh = "/zh/:year/:month/:slug/"
    en = "/en/:year/:month/:slug/"

[[menu.main]]
    name = "中文"
    url = "/zh/"
    weight = 1
[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 2

[[menu.zh]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.zh]]
    name = "日志"
    url = "/zh/"
    weight = 2
[[menu.zh]]
    name = "简历"
    url = "/zh/cv/"
    weight = 3
[[menu.zh]]
    name = "关于"
    url = "/zh/about/"
    weight = 4
[[menu.zh]]
    name = "订阅"
    url = "/zh/index.xml"
    weight = 5

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1  
[[menu.en]]
    name = "Post"
    url = "/en/"
    weight = 2
[[menu.en]]
    name = "CV"
    url = "/en/cv/"
    weight = 3
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 4
[[menu.en]]
    name = "RSS"
    url = "/en/index.xml"
    weight = 4

#[taxonomies]
#    project = "projects"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "index"

[Params]
    brand = "chen.fun"
    github = "https://github.com/ichenh/chen.fun/blob/main"

[Params.author]
    zh = "陈华"
    en = "Hua Chen"

[Params.footer]
    enable = true
    SiteDate = "" # 建站年份
    text = "CHEN, Hua" # 主要
    home = "[闽ICP备2020019883号-3](https://beian.miit.gov.cn/) | [又拍云 CDN](https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral)" # 仅显示在首页

[Params.edit]
    zh = "编辑此页"
    en = "Edit this page"

[Params.BackToTop]
    zh = "回到顶部"
    en = "Back to Top"

# front matter
# math  Boolean